language: node_js
node_js:
  - "stable"
cache:
  directories:
   - node_modules
script:
  - npm run affected:lint:ci
  - npm run affected:test:ci
  - npm run affected:e2e:ci
  - npm run affected:build:ci
on:
  branch: master
