language: node_js
node_js:
  - "stable"
cache:
  directories:
   - node_modules
script:
  - npm run affected:lint:ci
  - npm run affected:build:ci
  - npm run affected:test:ci
  - npm run affected:e2e:ci
on:
  branch: master
jobs:
  include:
    - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
        - npm run semantic-release
